---
# tasks file for apache
- name: Install libselinux-python
  yum: name=libselinux-python state=present
- name: Install Apache
  yum: name=httpd state=present
- name: Restart Apache service
  service: name=httpd enabled=yes state=started
- name: Copy configuration File from src to dest
  template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
  - Restart Apache  
- name: Creates directoy
  file: path=/var/www/html/ansible state=directory
- name: Copy Site Files
  template: src=templates/index.j2 dest="{{doc_root}}"/index.html mode=0644
